version: '3'

services:
  app-mysql-db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_DATABASE=app_demo
      - MYSQL_ROOT_HOST=%
    volumes:
      - appdatavolume:/var/lib/mysql

  app-java-container:
    image: app-java-container
    ports:
      - 8088:8080
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - app-mysql-db

# Names our volume
volumes:
  appdatavolume:
